DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    point INTEGER,
    password TEXT
);

DROP TABLE IF EXISTS point_logs;
CREATE TABLE IF NOT EXISTS point_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    point_diff INTEGER NOT NULL,
    created TEXT NOT NULL
);
